# Generated by Django 3.2.17 on 2023-02-12 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20230212_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1383c1eb-eb5f-474f-9093-4ab4b04ea1b0'), help_text='unique ID', primary_key=True, serialize=False),
        ),
    ]
