# Generated by Django 3.2.17 on 2023-02-18 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20230215_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance', to='catalogue.book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d93e355d-cfea-482a-9072-308a7b6f16d6'), help_text='unique ID', primary_key=True, serialize=False),
        ),
    ]
