# Generated by Django 3.2.17 on 2023-02-24 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20230218_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('745fbe56-4628-49a1-a45a-74ea661f86f1'), help_text='unique ID', primary_key=True, serialize=False),
        ),
    ]
